#!/usr/bin/env python3
"""Bake site/*.html into a TypeScript const module the Worker imports.

This eliminates the github.io proxy dependency: the Worker bundles the latest
HTML at deploy time, so /blake /progress /weekly etc. serve from inline strings
with zero upstream fetches.

Run order (sms.yml workflow):
  1. python sms_followup.py       (generates GHL artifacts)
  2. python blake_dashboard.py    (writes site/blake.html)
  3. python progress_dashboard.py (writes site/progress.html)
  4. ... (other generators)
  5. python bake_dashboards.py    <-- THIS — reads site/*.html, writes the TS file
  6. git commit + push            (the next CF Workers Build picks it up)

Output: workers/blake-post-call/src/dashboards.ts
        with const exports DASHBOARDS = { "blake.html": "...", "progress.html": "...", ... }
"""

from pathlib import Path

SITE_DIR = Path("site")
OUT = Path("workers/blake-post-call/src/dashboards.ts")

# Filenames we expose to the Worker. Keep in sync with the `gated` route map
# in index.ts. (Order doesn't matter; the const is a lookup table.)
DASHBOARDS = [
    "blake.html",
    "progress.html",
    "weekly.html",
    "priorities.html",
    "markets.html",
    "deals.html",
    "index.html",          # the follow-ups dashboard (served at /followups)
    "about.html",
    "setup.html",
    "ai-agents-plan.html",
    "sms-test.html",       # O2 entry-offer A/B/C test results
    "projects.html",       # Multi-project PoR canvas (new Roadmap landing)
    "por.html",            # Single-doc editorial APG Plan-of-Record
]


def ts_escape(s: str) -> str:
    """Escape a string for use inside a TypeScript template literal.

    Escapes: backslash, backtick, ${...} interpolations, and carriage returns.
    Leaves everything else (incl. newlines) as-is — template literals support
    multi-line content natively.
    """
    return (
        s.replace("\\", "\\\\")
        .replace("`", "\\`")
        .replace("${", "\\${")
        .replace("\r", "")
    )


def main() -> int:
    if not SITE_DIR.is_dir():
        print(f"[bake_dashboards] site/ not found at {SITE_DIR.resolve()} — skipping")
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("// Auto-generated by bake_dashboards.py — DO NOT EDIT BY HAND.")
    lines.append("// Each entry is the raw HTML of one site/*.html file at bake time.")
    lines.append("// Regenerated by sms.yml workflow after each Python generator step.")
    lines.append("")
    lines.append("export const DASHBOARDS: Record<string, string> = {")

    found = 0
    for name in DASHBOARDS:
        path = SITE_DIR / name
        if not path.exists():
            lines.append(f"  // {name} — missing at bake time; route falls back to github.io proxy")
            continue
        html = path.read_text(encoding="utf-8")
        escaped = ts_escape(html)
        lines.append(f"  {repr(name)}: `{escaped}`,")
        found += 1

    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[bake_dashboards] wrote {OUT} with {found}/{len(DASHBOARDS)} dashboards")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
