#!/usr/bin/env python3
"""
sync_por_sources.py — bundles APG-Vault POR markdown files into the Worker as
a TypeScript constant so /roadmap can parse + render them at request time.

Why this exists:
  The Worker cannot read Mido's local APG-Vault at request time. We embed the
  markdown at build time. Run this script whenever you edit a POR doc, then
  redeploy the Worker.

Convention for POR docs (Tyler-future-proofing — keep this stable):
  - File location: `<vault>/Strategy/<slug>.md` (any .md in Strategy/ is fair game)
  - H3 (`### Q3 2026`) marks quarter blocks
  - H4 (`#### July 2026`) marks month blocks inside a quarter
  - Tasks inside monthly tables use markdown table rows with a `Deadline`
    column in `YYYY-MM-DD` format — these get extracted as day-tagged events
  - Status strings recognized (case-insensitive substrings):
      LIVE / SHIPPED-IDLE / STUBBED / MISSING / BROKEN / DEFERRED

The Worker parser (`roadmap-tab.ts`) reads the embedded constant, so as long
as the markdown follows the convention above, no code changes are needed to
add a new POR doc — just drop a .md in `Strategy/` and re-run this script.

Usage:
  python sync_por_sources.py                      # default vault path
  python sync_por_sources.py --vault <path>       # custom vault
  python sync_por_sources.py --check              # exit 1 if output would differ
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, List

DEFAULT_VAULT = Path(os.path.expanduser("~/Documents/APG-Vault"))
OUTPUT_TS = Path(__file__).parent / "workers/blake-post-call/src/por-sources.ts"

# Files to include from Strategy/. We list explicitly (rather than glob) so a
# stray draft doesn't ship to Adam. To add a new POR doc to the dashboard,
# append its slug + filename here.
INCLUDED_DOCS: List[Dict[str, str]] = [
    {
        "slug": "apg-plan-of-record",
        "filename": "APG-Plan-of-Record.md",
        "label": "APG Plan of Record",
        "owner": "Mido Yasser",
    },
]


def load_doc(vault: Path, filename: str) -> str:
    p = vault / "Strategy" / filename
    if not p.exists():
        raise FileNotFoundError(f"POR doc not found: {p}")
    return p.read_text(encoding="utf-8")


def render_ts(entries: List[Dict[str, str]]) -> str:
    """Render TS file with a POR_SOURCES constant. JSON-encode each markdown
    body so we don't have to worry about backticks / `${}` / escapes."""
    items = []
    for e in entries:
        items.append(
            "  {\n"
            f"    slug: {json.dumps(e['slug'])},\n"
            f"    label: {json.dumps(e['label'])},\n"
            f"    owner: {json.dumps(e['owner'])},\n"
            f"    filename: {json.dumps(e['filename'])},\n"
            f"    markdown: {json.dumps(e['markdown'])},\n"
            "  },"
        )
    return (
        "// AUTO-GENERATED by sync_por_sources.py — do not hand-edit.\n"
        "// Source: APG-Vault/Strategy/*.md.\n"
        "// To add a new POR doc: edit sync_por_sources.py INCLUDED_DOCS, re-run, redeploy.\n"
        "\n"
        "export interface PorSource {\n"
        "  slug: string;\n"
        "  label: string;\n"
        "  owner: string;\n"
        "  filename: string;\n"
        "  markdown: string;\n"
        "}\n"
        "\n"
        "export const POR_SOURCES: PorSource[] = [\n"
        + "\n".join(items)
        + "\n];\n"
        "\n"
        "export const DEFAULT_POR_SLUG = POR_SOURCES[0]?.slug || \"\";\n"
        "\n"
        "export function findPorSource(slug?: string | null): PorSource | null {\n"
        "  if (!slug) return POR_SOURCES[0] || null;\n"
        "  return POR_SOURCES.find((p) => p.slug === slug) || null;\n"
        "}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", type=Path, default=DEFAULT_VAULT)
    ap.add_argument("--check", action="store_true", help="exit 1 if output would change")
    args = ap.parse_args()

    if not args.vault.exists():
        print(f"[sync_por] vault not found: {args.vault}", file=sys.stderr)
        return 2

    entries = []
    for d in INCLUDED_DOCS:
        md = load_doc(args.vault, d["filename"])
        entries.append({**d, "markdown": md})

    out = render_ts(entries)

    if args.check:
        existing = OUTPUT_TS.read_text(encoding="utf-8") if OUTPUT_TS.exists() else ""
        if existing != out:
            print(f"[sync_por] OUT OF DATE: {OUTPUT_TS}", file=sys.stderr)
            return 1
        print("[sync_por] up to date")
        return 0

    OUTPUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_TS.write_text(out, encoding="utf-8")
    total_bytes = sum(len(e["markdown"]) for e in entries)
    print(
        f"[sync_por] wrote {OUTPUT_TS} | {len(entries)} doc(s), "
        f"{total_bytes:,} bytes of markdown embedded"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
